# Site settings
title: 测试玉米君
url: "http://kwshare.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/kwshare.github.io" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
# timezone: Asia/Chongqing
description: >
  测试玉米君的博客.

# Your information
# email: adnnyone@outlook.com
author: 测试玉米君
avatar: "https://pic.cnblogs.com/avatar/1781125/20190913152759.png"
profile: 自动化测试工程师
twitter_username: twitter_username
github_username:  kwshare
cnblogs: adnny

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
# duoshuo_shortname: kwshare  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
